### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thomasfermi** [3F999/CARLA#1]
Hi @3F999 , I noticed that you are using code from my repository without attribution. For example for lane detection:
[my code](https://github.com/thomasfermi/Algorithms-for-Automated-Driving/blob/master/code/solutions/lane_detection/lane_detector.py)
[your code](https://github.com/3F999/CARLA/blob/main/src/lane_detector/lane_detector_custom.py)

You probably didn't notice the [license](https://github.com/thomasfermi/Algorithms-for-Automated-Driving/blob/master/LICENSE) on my repository. 
While I'm glad you find my code useful, I wanted to highlight the importance of acknowledging the licensing terms outlined in my repository. You are welcome to use my code, but it's required to include proper attribution when incorporating it into your repository. Simply adding a comment in your source code linking back to my repository would suffice.

**Comment by 3F999** [comment]
Hi Mario,
thank you for your Email, okay sure, Sorry for that, Im just not familier with Github would you guide me how should I do that? 
Regards,Behnaz    On Friday, March 29, 2024 at 03:10:53 PM GMT+1, Mario Theers ***@***.***> wrote:  
 
 


Hi @3F999 , I noticed that you are using code from my repository without attribution. For example for lane detection:
my code
your code

You probably didn't notice the license on my repository.
While I'm glad you find my code useful, I wanted to highlight the importance of acknowledging the licensing terms outlined in my repository. You are welcome to use my code, but it's required to include proper attribution when incorporating it into your repository. Simply adding a comment in your source code linking back to my repository would suffice.

**Comment by 3F999** [comment]
Dear @thomasfermi 
I have updated my ReadMe file to acknowledge your repository.
You can find it in the e8d7a36dd490483a0820e31a04de817141206881
If it needs any modifications, feel free to let me know.

**Comment by thomasfermi** [comment]
Thanks, for changing the README.

Maybe you could write that *some* of the source code is inspired by Algorithms for Automated Driving (in particular control and lane detection). I've also seen code in your repo about object detection, which I did not cover in my repo at all.

**Comment by 3F999** [comment]
Dear Mario,

thank you for your message, your right my main program is based on your depo but i will change it in feuture.
regards,
Behnaz
